version: '3.8'

services:
  web:
    build: .
    # Run the standard start script (or optionally bypass the statics setup script locally)
    command: ./start.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    depends_on:
      - tailwind

  tailwind:
    build: .
    command: npx @tailwindcss/cli -i input.css -o gamereviews/static/css/output.css --watch
    volumes:
      - .:/app
